# This file was generated by GoReleaser. DO NOT EDIT.
cask "tomato" do
  version "2.1.3"

  on_macos do
    on_arm do
      sha256 "ddd03668700fe56f34d0a719d4ddffd53c9efcb8eb991d1f5c7781a6481e2a4b"
      url "https://github.com/tomatool/tomato/releases/download/v#{version}/tomato_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "cfff89ce9f0ad4f2ebd90c04e4a95cb3931c5bfc39e621263a9c324a4ce069a4"
      url "https://github.com/tomatool/tomato/releases/download/v#{version}/tomato_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "723e5bec0977c65cb45d5e872af9bbe2f7b26114adfb1f0ab500621537323b1a"
      url "https://github.com/tomatool/tomato/releases/download/v#{version}/tomato_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1988441560c59789b58551a7defb42e9cfaf42aee42723032d8a44bc0eade8c3"
      url "https://github.com/tomatool/tomato/releases/download/v#{version}/tomato_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tomato"
  desc "Behavioral testing toolkit with built-in container orchestration"
  homepage "https://tomatool.github.io/tomato"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tomato"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tomato"]
    end
  end

  # No zap stanza required
end
