# This file was generated by GoReleaser. DO NOT EDIT.
cask "tomato" do
  name "tomato"
  desc "Behavioral testing toolkit with built-in container orchestration"
  homepage "https://tomatool.github.io/tomato"
  version "2.0.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tomato"

  on_macos do
    on_intel do
      url "https://github.com/tomatool/tomato/releases/download/v#{version}/tomato_#{version}_darwin_amd64.tar.gz"
      sha256 "7e681168304251dbf1df428b833e979dec7ee32e3bcb4be9e7c59b32882414aa"
    end
    on_arm do
      url "https://github.com/tomatool/tomato/releases/download/v#{version}/tomato_#{version}_darwin_arm64.tar.gz"
      sha256 "079e449fabebab1a79dec84ab61b9befe9abe908d68b221110a6da8fad9211bd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tomatool/tomato/releases/download/v#{version}/tomato_#{version}_linux_amd64.tar.gz"
      sha256 "e0e856e9ed6bd68dd2c2a17c1409b187e8d4e48588734c053e3fb058200b8448"
    end
    on_arm do
      url "https://github.com/tomatool/tomato/releases/download/v#{version}/tomato_#{version}_linux_arm64.tar.gz"
      sha256 "ff6ec8e9cf646441eadf1ba6f16da7804c27a7f816f00584d03e42d31babf444"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tomato"]
    end
  end

  # No zap stanza required
end
