# This file was generated by GoReleaser. DO NOT EDIT.
cask "tomato" do
  version "2.1.2"

  on_macos do
    on_arm do
      sha256 "aea606f79c33905b56bb8786fabba2c458d73646af2851093fd6074ba684c4e2"
      url "https://github.com/tomatool/tomato/releases/download/v#{version}/tomato_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c939cd076153bbb758fba9f5b74b35d1293dfd65ee9ff1b662bd6694c5e03241"
      url "https://github.com/tomatool/tomato/releases/download/v#{version}/tomato_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "19a39cc0841a23a4e9468533a8e4ab857da25675a739c78d95e07b159f296f15"
      url "https://github.com/tomatool/tomato/releases/download/v#{version}/tomato_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "be249553e80357ad04608f101a85ced9f71868837343a348ef12822719f33347"
      url "https://github.com/tomatool/tomato/releases/download/v#{version}/tomato_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tomato"
  desc "Behavioral testing toolkit with built-in container orchestration"
  homepage "https://tomatool.github.io/tomato"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tomato"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tomato"]
    end
  end

  # No zap stanza required
end
