# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tomato < Formula
  desc "Behavioral testing toolkit with built-in container orchestration"
  homepage "https://tomatool.github.io/tomato"
  version "2.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tomatool/tomato/releases/download/v2.0.3/tomato_2.0.3_darwin_amd64.tar.gz"
      sha256 "989f58ba09276351d3d99ce1a9619fddb7213e765d69c716fd7d59785cb95b24"

      def install
        bin.install "tomato"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tomatool/tomato/releases/download/v2.0.3/tomato_2.0.3_darwin_arm64.tar.gz"
      sha256 "965987e4791aa05ab6f324ce1d7613d1cc33c10e22d1bd50f62c6fb112dee420"

      def install
        bin.install "tomato"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tomatool/tomato/releases/download/v2.0.3/tomato_2.0.3_linux_amd64.tar.gz"
      sha256 "589146a903a0f42f29095d33bbd65ee2f2c1cf31b815bcc76d48d754f85e39ef"
      def install
        bin.install "tomato"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tomatool/tomato/releases/download/v2.0.3/tomato_2.0.3_linux_arm64.tar.gz"
      sha256 "d7f65f79572e55372c6f001ad9e8267f430db33a748704572c3bf7fc8aedbfbf"
      def install
        bin.install "tomato"
      end
    end
  end

  test do
    system "#{bin}/tomato", "--version"
  end
end
