# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tomato < Formula
  desc "Behavioral testing toolkit with built-in container orchestration"
  homepage "https://tomatool.github.io/tomato"
  version "2.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tomatool/tomato/releases/download/v2.0.2/tomato_2.0.2_darwin_amd64.tar.gz"
      sha256 "508bb82fc20e91fdae5cd5743b93abce14cfadb1ca63012dc2aa02e806d77310"

      def install
        bin.install "tomato"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tomatool/tomato/releases/download/v2.0.2/tomato_2.0.2_darwin_arm64.tar.gz"
      sha256 "4cf9df602b10831645cbb3e0cbde2140b1d0f01b846ec30ed46099aaca4d3493"

      def install
        bin.install "tomato"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tomatool/tomato/releases/download/v2.0.2/tomato_2.0.2_linux_amd64.tar.gz"
      sha256 "d9ed3646c1f565bb14a52016d97b914d226e87550a067ad77c513f336ef8e878"
      def install
        bin.install "tomato"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tomatool/tomato/releases/download/v2.0.2/tomato_2.0.2_linux_arm64.tar.gz"
      sha256 "0c298bbb62ba9342f13783ab2d70550236a59a93ec3df0db7b168cc07146e301"
      def install
        bin.install "tomato"
      end
    end
  end

  test do
    system "#{bin}/tomato", "--version"
  end
end
